---
- hosts: swarm_manager:swarm_worker
  become: true
  become_user: root
  vars:
    efs_mount_point: /var/lib/docker/volumes
  pre_tasks:
    - include: base/pre_tasks.yaml
  roles:
    - system-update
  tasks:
    - include: base/install_docker.yaml
    - include: base/mount_efs.yaml
    - include: base/swarm_cluster.ansible.yaml
    - include: base/install_sweady.ansible.yaml