---
- hosts: swarm_manager:swarm_worker:name_swarm_manager-1
  become: true
  become_user: root
  vars:
    efs_mount_point: /var/lib/docker/volumes
  tasks:
    - include: base/00_pre_tasks.yaml
    - include: base/01_update_system.yaml
    - include: base/02_install_docker.yaml
    - include: base/03_mount_efs.yaml
    - include: base/04_create_swarm.yaml
    - include: base/05_install_sweady.yaml