---
    - name: "[GLOBAL] Clear file"
      command: rm -rf /etc/apt/apt.conf.d/50unattended*

    - name: "[GLOBAL] Kill apt-daily"
      command: systemctl kill --kill-who=all apt-daily.service
      ignore_errors: yes

    - name: "[GLOBAL] Stop apt auto update (timer)"
      systemd: name=apt-daily.timer state=stopped enabled=no

    - name: "[GLOBAL] Stop apt auto update (service)"
      systemd: name=apt-daily.service state=stopped enabled=no

    - name: "[GLOBAL] Clean DPKG"
      command: dpkg --configure -a