---
    - name: "[MANAGER] Clone project"
      git:
        repo: https://github.com/Sweady/Sweady.git
        dest: /tmp/sweady
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Ensures data dir exists"
      file: path=/var/lib/docker/volumes/monitoring_prometheus_config/_data/ state=directory
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Config for Prometheus"
      copy:
        src: ../docker-compose/monitoring/prometheus/prometheus.yml
        dest: /var/lib/docker/volumes/monitoring_prometheus_config/_data/prometheus.yml
        owner: root
        group: root
        mode: 0755
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Data for Logstash"
      file: path=/var/lib/docker/volumes/log_logstash_config/_data/  state=directory
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Config for Logstash"
      copy:
        src: ../docker-compose/log/conf/gelf.conf
        dest: /var/lib/docker/volumes/log_logstash_config/_data/gelf.yml
        owner: root
        group: root
        mode: 0755
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Sleep"
      command: sleep 30
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Deploy Sweady stack"
      command: docker stack deploy -c /tmp/sweady/engine/docker-compose/sweady/docker-compose.yml sweady
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Deploy logging stack"
      command: docker stack deploy -c /tmp/sweady/engine/docker-compose/log/docker-compose.yml sweady_loglog
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Deploy monitoring stack"
      command: docker stack deploy -c /tmp/sweady/engine/docker-compose/monitoring/docker-compose.yml sweady_monitoring
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Wait grafana"
      wait_for:
        port: 3000
        delay: 20
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Deploy Grafana Datasource"
      command: "curl -X POST http://127.0.0.1:3000/api/datasources --header 'Content-Type: application/json' --data-binary '@/tmp/sweady/engine/docker-compose/monitoring/grafana/datasource/prometheus.json'"
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Deploy Grafana Dashboard -> Docker"
      command: "curl -X POST http://127.0.0.1:3000/api/dashboards/import --header 'Content-Type: application/json' --data-binary '@/tmp/sweady/engine/docker-compose/monitoring/grafana/dashboards/docker_monitoring.json'"
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Deploy Grafana Dashboard -> Prometheus"
      command: "curl -X POST http://127.0.0.1:3000/api/dashboards/import --header 'Content-Type: application/json' --data-binary '@/tmp/sweady/engine/docker-compose/monitoring/grafana/dashboards/prometheus.json'"
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[MANAGER] Deploy Grafana Dashboard -> Docker Swarm"
      command: "curl -X POST http://127.0.0.1:3000/api/dashboards/import --header 'content-Type: application/json' --data-binary '@/tmp/sweady/engine/docker-compose/monitoring/grafana/dashboards/docker_swarm.json'"
      when: "inventory_hostname == groups.swarm_manager[0]"