---
  - name: Add key for Docker
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present

  - name: Add repo for Docker
    apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu xenial stable"
      state: present
      filename: "docker"

  - name: Install Docker
    apt:
      name: docker-ce
      state: present
      update_cache: yes

  - name: Active Docker Boot
    systemd: name=docker enabled=yes

  - name: Fix vm.max_map_count
    command: sysctl -w vm.max_map_count=262144