---
  - name: "apt| install nfs-common"
    apt:
      name: nfs-common
      state: installed

  - name: "mount| create directory"
    file:
      path: "{{ efs_mount_point }}"
      state: directory

  - name: "mount| mount efs volumes"
    mount:
      name: "{{ efs_mount_point }}"
      src: "{{ efs_url }}:/"
      fstype: nfs4
      opts: nfsvers=4.1
      state: mounted
