---
    - name: Define tmp var swarm_manager_ip
      set_fact:
        swarm_manager_ip="{% for host in groups['swarm_manager'] %}{{ hostvars[host]['ansible_default_ipv4']['address'] }}{% endfor %}"

    - name: "[swarm_manager] swarm init"
      command: docker swarm init --advertise-addr {{ swarm_manager_ip }}
      ignore_errors: yes
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: "[swarm_manager] get token"
      command: docker swarm join-token -q worker
      register: swarm_manager_token_worker_tmp
      when: "inventory_hostname == groups.swarm_manager[0]"

    - name: Define tmp var swarm_manager_token_worker
      set_fact:
        swarm_manager_token_worker="{% for host in groups['swarm_manager'] %}{{ hostvars[host]['swarm_manager_token_worker_tmp'] }}{% endfor %}"

    - name: "[swarm_worker] slave join master"
      command: docker swarm join --token {{ swarm_manager_token_worker.stdout }} {{ swarm_manager_ip }}:2377
      when: inventory_hostname in groups['swarm_worker']
